name: CI/CD Pipeline for React App on GCP

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Authenticate Docker to GCR
      - name: Authenticate Docker to GCR
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/react-app-test-450006/reactfirstapp:latest .

      # Push the Docker image to GCR
      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/react-app-test-450006/reactfirstapp:latest

      # Deploy to GKE
      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --region ${{ secrets.GKE_REGION }} --project ${{ secrets.GCP_PROJECT_ID }}
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
